package Cadastro;

import java.awt.Color;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 182400306
 */
public class Frame extends javax.swing.JFrame {

    private final Calculos objCalc = new Calculos();
    private FileWriter rowFile;
    private PrintWriter editRowFilePrintWriter;

    private final DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        tableModel.addColumn("Nome");
        // tableModel.addColumn("RG");
        // tableModel.addColumn("CPF");
        // tableModel.addColumn("Sexo");
        tableModel.addColumn("Palpite");
        tableModel.addColumn("Menor Diferença");
        tableModel.addColumn("Numero Proximo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        labelNumSorteados = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputPalpite = new javax.swing.JTextField();
        buttonSortear = new javax.swing.JButton();
        buttonRowToTXT = new javax.swing.JButton();
        buttonTableToTXT = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro");

        jLabel2.setText("Nome:");

        inputNome.setMaximumSize(new java.awt.Dimension(80, 22));
        inputNome.setMinimumSize(new java.awt.Dimension(80, 22));
        inputNome.setPreferredSize(new java.awt.Dimension(80, 22));
        inputNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNomeKeyTyped(evt);
            }
        });

        buttonOK.setText("Registrar Palpite");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(mainTable);

        labelNumSorteados.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelNumSorteados.setText(".");

        jLabel3.setText("Palpite");

        inputPalpite.setMaximumSize(new java.awt.Dimension(80, 22));
        inputPalpite.setMinimumSize(new java.awt.Dimension(80, 22));
        inputPalpite.setPreferredSize(new java.awt.Dimension(80, 22));

        buttonSortear.setText("Sortear 5 Numeros");
        buttonSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortearActionPerformed(evt);
            }
        });

        buttonRowToTXT.setText("Guardar Linha em TXT");
        buttonRowToTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRowToTXTActionPerformed(evt);
            }
        });

        buttonTableToTXT.setText("Guardar Tabela Inteira em TXT");
        buttonTableToTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableToTXTActionPerformed(evt);
            }
        });

        buttonDelete.setText("Deletar Palpite Selec.");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRowToTXT)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTableToTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSortear)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(21, 21, 21)
                                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(inputPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonOK)
                            .addComponent(buttonDelete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumSorteados)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDelete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(labelNumSorteados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(buttonRowToTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSortear)
                    .addComponent(buttonTableToTXT))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNomeKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isAlphabetic(c)) {
            evt.consume();
            inputNome.setForeground(Color.RED);
        } else {
            inputNome.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_inputNomeKeyTyped

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        String[] newRow = {inputNome.getText(), inputPalpite.getText(), "-", "-"};
        tableModel.addRow(newRow);
        mainTable.setModel(tableModel);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortearActionPerformed
        int[] sorteados = objCalc.arrayResults(5);
        String sorteadosString = "";
        for (int i = 0; i < sorteados.length; i++) {
            sorteadosString += String.valueOf(sorteados[i]) + " ";
        }
        labelNumSorteados.setText("Os numeros sorteados são: " + sorteadosString);
        for (int i = 0; i < mainTable.getRowCount(); i++) {
            int valor;
            valor = Integer.parseInt(mainTable.getValueAt(i, 1).toString());
            int diferenca = objCalc.calcularDiferença(sorteados, valor);
            mainTable.setValueAt(diferenca, i, 2);
        }
        
        for (int i = 0; i < mainTable.getRowCount(); i++) {
            int valor;
            valor = Integer.parseInt(mainTable.getValueAt(i, 1).toString());
            int numProximo = objCalc.numeroProximo(sorteados, valor);
            mainTable.setValueAt(numProximo, i, 3);
        }
    }//GEN-LAST:event_buttonSortearActionPerformed

    private void buttonRowToTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRowToTXTActionPerformed
        try {
            int selectedRow = mainTable.getSelectedRow();
            if (selectedRow != -1) {

                String[] rowValues = new String[mainTable.getColumnCount()];
                for (int i = 0; i < rowValues.length; i++) {
                    rowValues[i] = mainTable.getValueAt(selectedRow, i).toString();
                }
                rowFile = new FileWriter("arquivolinha.txt");
                editRowFilePrintWriter = new PrintWriter(rowFile);
                for (int i = 0; i < rowValues.length; i++) {
                    if (i == 0) {
                        editRowFilePrintWriter.printf("Nome: " + rowValues[i] + "\n");
                        editRowFilePrintWriter.flush();
                    }
                    if (i == 1) {
                        editRowFilePrintWriter.printf("Palpite: " + rowValues[i] + "\n");
                        editRowFilePrintWriter.flush();
                    }
                    if (i == 2) {
                        editRowFilePrintWriter.printf("Diferença: " + rowValues[i] + "\n");
                        editRowFilePrintWriter.flush();
                    }
                }
                rowFile.close();
                editRowFilePrintWriter.close();
            }
        } catch (IOException exception) {
            System.out.println(exception);
        }
    }//GEN-LAST:event_buttonRowToTXTActionPerformed

    private void buttonTableToTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableToTXTActionPerformed
        try {
            FileWriter tableFileWriter = new FileWriter("arquivotabela.txt");
            PrintWriter editTableFilePrintWriter = new PrintWriter(tableFileWriter);
            
            editTableFilePrintWriter.printf("Nome\t Palpite\t Diferença\t NumProximo\n");
             for (int row = 0; row < mainTable.getRowCount(); row++) {
                for (int col = 0; col < mainTable.getColumnCount(); col++) {
                    editTableFilePrintWriter.print(mainTable.getValueAt(row, col).toString() + "\t");
                }
                editTableFilePrintWriter.println();
            }
            tableFileWriter.close();
            editTableFilePrintWriter.close();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_buttonTableToTXTActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonRowToTXT;
    private javax.swing.JButton buttonSortear;
    private javax.swing.JButton buttonTableToTXT;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPalpite;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNumSorteados;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
